name: ci
on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'typings/**'
      - 'template/**'
      - 'package.json'
      - 'yarn.lock'
    branches:
      - '*'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 30
          persist-credentials: false

#      - name: Yarn install
#        uses: bahmutov/npm-install@v1
#        with:
#          install-command: yarn --frozen-lockfile --silent

      - name: Yarn install
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn test
